/* An alternate method for doing question 1 and 2 on the prac*/

/* QUESTION 1 */

CREATE SEQUENCE "EMPNO_SEQ" MINVALUE 1000 MAXVALUE 999999999999
INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER "BI_EMP"
BEFORE INSERT ON "EMP"
FOR EACH ROW
DECLARE
	next_seq INTEGER;
BEGIN
	next_seq := "EMPNO_SEQ".NEXTVAL;
	:NEW.EMPNO := next_seq;
END;

/* QUESTION 2 */

CREATE SEQUENCE "DEPTNO_SEQ" MINVALUE 10 MAXVALUE 999999999990
INCREMENT BY 10 START WITH 50;

CREATE OR REPLACE TRIGGER "BI_DEPT"
	BEFORE INSERT ON "DEPT"
	FOR EACH ROW
DECLARE
	next_seq INTEGER;
BEGIN
	next_seq := "DEPTNO_SEQ".NEXTVAL;
	:NEW.DEPTNO := next_seq;
END;
/

/* DIY 1 */

TRUNCATE TABLE EMP;
DROP TRIGGER "BI_EMP";

ALTER TABLE EMP
MODIFY EMPNO VARCHAR2(10);

CREATE OR REPLACE TRIGGER "BI_EMP" 
	BEFORE INSERT ON "EMP"
	FOR EACH ROW
DECLARE
	emp_count NUMBER;
	dept_initial VARCHAR(3);
BEGIN
	SELECT COUNT(*) INTO emp_count FROM EMP WHERE DEPTNO=:NEW.DEPTNO;
	emp_count := emp_count + 1;
	SELECT SUBSTR(DNAME, 1, 3) INTO DEPT_INITIAL FROM DEPT WHERE DEPTNO=:NEW.DEPTNO;
	:NEW.EMPNO := CONCAT(dept_initial, TO_CHAR(emp_count)); 
END;
/

INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Albert Aloysius', 'Engineer', null, '02-May-05', 10000, 10);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Yule Zane', 'Engineer', null, '04-Oct-00', 10000, 10);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Antwan Arion', 'Engineer', null, '03-Oct-00', 10010, 30);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Adit Ailill', 'Engineer', null, '02-Oct-06', 10010, 30);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Auburn Azaria', 'Consultant', null, '04-Oct-07', 10020, 10);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Alp Amory', 'Consultant', null, '03-Oct-00', 10020, 10);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Beale Bern', 'Consultant', null, '02-Oct-00', 10030, 10);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Aristos Arvin', 'Consultant', null, '04-Apr-00', 10030, 40);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Bradshaw Briar', 'Consultant', null, '03-Jan-00', 10040, 40);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Azhar Bardolph', 'Consultant', null, '02-Apr-00', 10040, 40);
INSERT INTO EMP (ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO) VALUES('Cairbre Caradoc', 'Consultant', null, '04-Oct-10', 10050, 40);

/* DIY 2 */

CREATE OR REPLACE TRIGGER "EMP_SAL"
	BEFORE INSERT ON "EMP"
	FOR EACH ROW
DECLARE
	mgr_sal NUMBER;
BEGIN
	IF (:NEW.MGR IS NOT NULL) THEN
		SELECT SAL INTO MGR_SAL FROM EMP WHERE EMPNO = :NEW.MGR;
		IF (MGR_SAL < :NEW.SAL) THEN
			RAISE_APPLICATION_ERROR(-20101, 'THE EMPLOYEE SALARY CANNOT BE HIGHER THAN THE MANAGER SALARY');
		END IF;
	END IF;
END;
/
	
	
	
	
	
	
	
	
